redwoodjs/learn.redwoodjs.com

- src/css/custom.css
Got the main colors in there but I don't see an easy way to change like buttons or the footer background...I see additional variables in the web inspector, but when I try changing them nothing happens:
```css
/* /src/css/custom.css */
:root {
--ifm-color-primary: #BF4722;
--ifm-color-primary-dark: #682712;
--ifm-color-primary-darker: #341309;
--ifm-color-primary-darkest: #1f0a04;
--ifm-color-primary-light: #E38163;
--ifm-color-primary-lighter: #EBA48E;
--ifm-color-primary-lightest: #F3C7BA;
--ifm-code-font-size: 95%;
--ifm-footer-background-color: #682712;
}
```
Closes #7
> Add colors from redwoodjs.com

- README.md
fix #27  replacing the deployment URL in README.md
> fix #24 replacing the deployment URL in README.md

- docusaurus.config.js
- src/css/custom.css
> Fix code color in dark mode

- docusaurus.config.js
- src/css/custom.css
> Adds Algolia serach

- src/css/custom.css
Closes #39
Let me know how this looks @M0nica!
> Footer styles to address contrast

- sidebars.js
Adds missing page from sidebar
> Add tutorial2/our-first-test to sidebar

- docs/tutorial/everyones-favorite-thing-to-build-forms.md
Found a small code block highlight issue.
In previous code blocks
```
<TextField name="input" />
```
changes to 
```
<TextField name="name" />
```
So to highlight this line as well to avoid missed copy / paste lines
> Update code highlight in everyone-s-favorite-thing-to-build-forms

- docs/tutorial/authentication.md
This changed when we merged the prerender changes
> authentication.md: index.js -> App.js

- docs/tutorial/authentication.md
Auth isn't handled by a generator anymore, it's now a setup command.
> authentication.md: generator -> setup command

- docs/tutorial/saving-data.md
> Swaps out Flash for toast, updates screenshot

- docs/tutorial/cells.md
> Cells Section - Fix broken link

- docs/tutorial2/our-first-story.md
Corresponding codeblock update to PR https://github.com/redwoodjs/redwood-tutorial/pull/13; just removes some superfluous divs / updates the styling.
> Remove superfluous divs

- docs/tutorial/saving-data.md
> turn on syntax highlighting

- docusaurus.config.js
- i18n/es/docusaurus-theme-classic/footer.json
- i18n/es/docusaurus-theme-classic/navbar.json
- src/components/HelpUsTranslateBanner.js
Adds Spanish Tutorial pt I (Translated by @pdjota), and Spanish UI translations
> Add Spanish tutorial part I, UI

- README.md
- docs/tutorial2/creating-a-comment-form.md
Hey, yet again. 
All the best and a great weekend. 
António
> assorted spelling tweaks

- docs/tutorial/deployment.md
> change `the` to `to`

- docs/tutorial/getting-dynamic.md
I noticed strange grammar in the description of fields in getting dynamic when following through the tutorial. This is one alternative improvement.
> Update getting-dynamic.md list grammar

- docs/tutorial/authentication.md
Fixing the wrap for the BlogLayout and adding back the wrap for the PostsLayout
> Update to Routes.js

- docs/tutorial2/our-first-story.md
We want to highlight the summary prop line
> tutorial: first story post summary highlight

- docs/tutorial2/adding-comments-to-the-schema.md
Closes #148.
Ping ping @cannikin
> [v0.37.0] Updates for scenario syntax

- docs/tutorial/wrapping-up.md
- docs/tutorial2/wrapping-up.md
The release date is said to be March 2021. Have updated this to say 2022.
> Update planned release date of Redwood 1.0

- docs/tutorial/prerequisites.md
Reverts redwoodjs/learn.redwoodjs.com#169
> Revert "Update prerequisites with Windows setup cookbook"

- docs/tutorial/authentication.md
- docs/tutorial/deployment.md
- docs/tutorial/layouts.md
- docs/tutorial/our-first-page.md
- docs/tutorial/routing-params.md
- docs/tutorial/saving-data.md
- docs/tutorial/side-quest-how-redwood-works-with-data.md
- docs/tutorial2/our-first-test.md
Hey all, 
All the best, 
António
> assorted typo squashing

- docs/tutorial2/prerequisites.md
Entering that command now gives you the error: WARNING: deprecated "tailwind" command
See "rw setup ui tailwindcss" command:
> updated tailwind to tailwindcss

- docs/tutorial/building-a-form.md
In `/tutorial/building-a-form`
- Update the code highlights referencing the Contact code changes
> docs(building-a-form): Update contact highlights

- docs/tutorial/cells.md
- docs/tutorial/routing-params.md
- docs/tutorial/side-quest-how-redwood-works-with-data.md
- Fixing a minor typo.
- Fixing the export for `Routes.js`
- Adding `@requireAuth` to the queries inside `posts.sdl.js`. It would throw an error without these params set.
@cannikin
> Readme fixes

- docs/tutorial2/role-based-authorization-control-rbac.md
Add path comment line to the comment.sdl.js for consistency.
> Update role-based-authorization-control-rbac.md - add file path to example

- docs/tutorial/cells.md
Added "api/" to the file path and remove a "/" before a "web/..." file path.
> Tutorial1: Cells: Added "api/" & remove a "/"
