docs/tutorial/a-second-page-and-a-link.md
docs/tutorial/authentication.md
docs/tutorial/cells.md
docs/tutorial/deployment.md
docs/tutorial/everyones-favorite-thing-to-build-forms.md
docs/tutorial/getting-dynamic.md
docs/tutorial/layouts.md
docs/tutorial/routing-params.md
docs/tutorial/saving-data.md
to-upload/fr/a-second-page-and-a-link.md
to-upload/fr/authentication.md
to-upload/fr/cells.md
to-upload/fr/deployment.md
to-upload/fr/everyones-favorite-thing-to-build-forms.md
to-upload/fr/getting-dynamic.md
to-upload/fr/layouts.md
to-upload/fr/routing-params.md
to-upload/fr/saving-data.md

Updated markdown syntax to comply with `remark` parser used in Docusaurus. 
Before: 
```
```javascript{3-8}
```
After: 
```
```javascript {3-8}
```

Update markdown syntax for remark code line highlighting

---

src/pages/docs/index.js
src/pages/docs/tutorial/index.js

Adds redirects from `/docs` and `/docs/tutorial` to "Welcome to Redwood" tutorial
Works for both English:
```
yarn start 
/docs           -> /docs/tutorial/welcome-to-redwood
/docs/tutorial  -> /docs/tutorial/welcome-to-redwood
```
and other locales (ex: French):
```
yarn start --locale fr
/fr/docs           -> /fr/docs/tutorial/welcome-to-redwood
/fr/docs/tutorial  -> /fr/docs/tutorial/welcome-to-redwood
```

Add redirects from /docs and /docs/tutorial

---

i18n/fr/docusaurus-plugin-content-docs/current.json
i18n/fr/docusaurus-theme-classic/footer.json
i18n/fr/docusaurus-theme-classic/navbar.json

I did the french translation for the footer. Can you review it? If there are any queries, free free to mention them.

French translation for footer #32

---

src/css/custom.css

This pull request increases the color contrast for comments in code snippets from 2.2 to 5.05 in order to address https://github.com/redwoodjs/learn.redwoodjs.com/issues/38
This change can be viewed by visiting https://deploy-preview-42--learn-redwood.netlify.app/docs/tutorial/cells/#our-first-cell and inspecting the code comment to see the 5.05 contrast both in light and dark mode.
| Before Changes       (contrast - 2.2)                                                                                                                                                                                                                                                                                                                           | After Changes       (contrast - 5.05) …

increase contrast for code comments

---

docusaurus.config.js

This should be the URL of the site, not URL of the git repo
https://v2.docusaurus.io/docs/next/docusaurus.config.js/#url
This should fix the bad sitemap containing github.com:
- https://learn-redwood.netlify.app/sitemap.xml
- https://learn-redwood.netlify.app/fr/sitemap.xml
That prevents Algolia Docsearch to work on `/fr/` urls

Fix Docusaurus url

---

docusaurus.config.js

Hi
This PR to edit this [link](https://github.com/redwoodjs/learn.redwoodjs.com) to [this](https://github.com/redwoodjs/learn.redwoodjs.com/blob/main/) at `docusaurus.config.js > prests > docs > editUrl`
The changes in branch `feat/editpagelink`
I hope this works fine
If it need another update I hope anyone help me
Thanks

Update link at docusaurus.config.js > prests > docs > editUrl

---

i18n/fr/docusaurus-plugin-content-docs/current/tutorial/a-second-page-and-a-link.md
i18n/fr/docusaurus-plugin-content-docs/current/tutorial/administration.md
i18n/fr/docusaurus-plugin-content-docs/current/tutorial/authentication.md
i18n/fr/docusaurus-plugin-content-docs/current/tutorial/installation-starting-development.md
i18n/fr/docusaurus-plugin-content-docs/current/tutorial/layouts.md
i18n/fr/docusaurus-plugin-content-docs/current/tutorial/redwood-file-structure.md
i18n/fr/docusaurus-plugin-content-docs/current/tutorial/saving-data.md

Adds a custom edit url back to newly translated French pages
Note: this is a temporary fix - as right now each Crowdin PR deletes the custom edit url because it doesn't exist in the source. I'm in contact with docusaurus to find a better way

Add custom edit url to french pages

---

docusaurus.config.js
src/css/custom.css

This banner appears at the top of all pages, calling for help with French and Spanish translation.
It disappears on scroll.
dark mode
light mode
on scroll (disappears)

Add announcement banner call for translators

---

docusaurus.config.js

Makes it clear that Docs and Cookbook link to .com

Add icons for external linking, add Cookbooks link

---

docs/tutorial/authentication.md
docs/tutorial/cells.md
docs/tutorial/everyones-favorite-thing-to-build-forms.md
docs/tutorial/layouts.md
docs/tutorial/routing-params.md
docs/tutorial/saving-data.md

Updates the tutorial so that it uses the new `<Set>` component to wrap layouts around pages in the Routes.js file, instead of each page importing the layout itself.

Switch to using `<Set>`

---

docs/tutorial2/multiple-comments.md

Was following the 2nd tutorial, ran into some issues of 'standard' being not defined, turns out I missed copying it due to a missing highlight. Added it in order to help others.

Fix missing line highlight in multiple-comments.md

---

docs/tutorial2/creating-a-comment-form.md

Found a couple of missing higlights in the creating-a-comment-form.md section of the tutorial.
I could've extended the range of the 35-39, but since that code block refers to the form error, I choose to do line 34 separately. If it's preferred I use the range, let me know and I'll update it.

Fix a couple of missing code higlights in creating-a-comment-form.md

---

docs/tutorial2/role-based-authorization-control-rbac.md

The example was a little unclear on it having to be added to the file so I added the `// ...` section and correctly highlighted the newly added lines.

Fix syntax highlighting for delete comment test in rbac example

---

docs/tutorial/getting-dynamic.md

Docs updates for https://github.com/redwoodjs/redwood/pull/2609
To Do:
@jtoar Can you please check here? Is this the right way to do?
Feel free to scrape it if completely wrong, will re-create with correct instructions. :)

[v0.33] Scaffold now wraps Routes in Set component

---

docs/tutorial/prerequisites.md

Only Node.js LTS is currently supported, which is v14. Both v15 and v16 will error.

pin Node.js prerequisite to 14.x

---

docs/tutorial2/role-based-authorization-control-rbac.md
docs/tutorial2/welcome-to-redwood-part-ii-redwoods-revenge.md

It seems the consensus is that the "A" in RBAC stands for "Access", not Authorisation.
There are other locations for this usage, for example: the url / page name: `role-based-authorization-control-rbac.md`.
This PR only addresses content: RBAC page & welcome page.

rbac: a for access

---

docs/tutorial2/role-based-authorization-control-rbac.md

It seems that the web-side test syntax was used to improperly test the comment service on the api side.
Tests don't use `db` in this tutorial.
Also we needed to import `deleteComment`.

tutorial: correct syntax for api test

---

docs/tutorial/prerequisites.md

Solves the issue ([#3728](https://github.com/redwoodjs/redwood/issues/3728)) I had picking the right node version, 14.0.0 wasn't working for me. It would probably be better to either keep the version number updated, or just refer to node.js LTS, as 14.0.0 was an "even" version, but it's not working either. This could also lead to a page / table showing each an every node version that's compatible with redwood, instead of making newcomers guess.

Updated suggested node version in Prequisites

---

docs/tutorial2/adding-comments-to-the-schema.md

At this point we create a new sdl `comment`. The correct file name for this graphql file is `comments.sdl.js`

fix file name

---

docs/tutorial/prerequisites.md

Update prerequisites with Windows development setup cookbook to give a complete guide of how to develop with Redwood on Windows.
Wait for [redwoodjs/redwoodjs.com#922](https://github.com/redwoodjs/redwoodjs.com/pull/922) before merge.
cc @clairefro 😊

Update prerequisites with Windows setup cookbook

---

docs/tutorial2/our-first-story.md
docs/tutorial2/our-first-test.md

Fixes this issue: [Tutorial II provides sample blog post body with extra spacing, BlogPost test fails by default](https://github.com/redwoodjs/learn.redwoodjs.com/issues/180)
This PR fixes a really minor bug, so it's not a high priority.

Remove extra spaces from sample BlogPost body

---

docs/tutorial2/our-first-story.md
docs/tutorial2/our-first-test.md

Corrects line highlighting oversight in [this PR](https://github.com/redwoodjs/learn.redwoodjs.com/pull/181), addresses [this issue](https://github.com/redwoodjs/learn.redwoodjs.com/issues/180).
I also slightly refactored a related code block, and this time I did remember to adjust code highlighting accordingly!

Correct BlogPost story and test line numbers

---

docs/tutorial2/adding-comments-to-the-schema.md

This PR adds missing auth decorators from `Comment` mutations in [sample sdl code](https://learn.redwoodjs.com/docs/tutorial2/adding-comments-to-the-schema#building-out-the-service) in Tutorial II.  It also adds a small explanation for why `deleteComment` should require authorization.

Comment mutations missing auth decorators in sample sdl code

---

docs/tutorial2/prerequisites.md

Now that https://github.com/redwoodjs/redwood-tutorial/pull/18 has been merged, the tutorial documentation should be updated.
According to https://www.prisma.io/docs/guides/database/seed-database#integrated-seeding-with-prisma-migrate, seeding now happens automatically in `prisma migrate dev`.  I know seeding automatically occurred after running `yarn rw prisma migrate dev` while I was using SQLite, but after switching to postgresql I had to run `yarn rw prisma db seed` again.  I don't think we should list it as a "get up and running" command in the README file, because with the initial SQLite configuration this command will end up double-seeding the database (so the user will start with 6 posts, 2 copies of each seed post).

Remove prisma seed command

---

docs/tutorial/routing-params.md

Name was changed from article to blogPost in user example causing crashing.

Fix wrong route name.

---

docs/tutorial2/our-first-test.md

Example uses Article prop post but it should be article (https://github.com/redwoodjs/redwood-tutorial/blob/main/web/src/components/Article/Article.js)

Fix our-first-test example

---

.github/issue_template.md
.github/pull_request_template.md

We've moved the docs to the [redwoodjs/redwood](https://github.com/redwoodjs/redwood/tree/main/docs/docs) repo!

Add issue and pr templates

---

docs/tutorial2/role-based-authorization-control-rbac.md

fix wrongly placed parenthesis "...we'll (try) to migrate..." -> "...we'll (try to) migrate..."
🚨 HEADS UP
In preparation for the 1.0.0 release, the Redwood Docs have been integrated with the main Redwood Framework redwoodjs/redwood repo. We are in the final stages of the migration. Once complete, this repo will be archived.
> Please do not open new PRs here. Instead, open them at https://github.com/redwoodjs/redwood/pulls
The new doc site uses Docusaurus. The Docs are located here:
- https://github.com/redwoodjs/redwood/tree/main/docs

 (fix typo) Update role-based-authorization-control-rbac.md
